"""empty message

Revision ID: 612a8ae836be
Revises: 6218f6cc086f
Create Date: 2022-05-10 10:15:25.699990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '612a8ae836be'
down_revision = '6218f6cc086f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cat', sa.Column('human_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cat', 'human', ['human_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cat', type_='foreignkey')
    op.drop_column('cat', 'human_id')
    # ### end Alembic commands ###
